# Generated by Django 3.0 on 2021-04-07 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubservs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='posts',
        ),
    ]
