# Generated by Django 3.0 on 2021-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubservs', '0005_auto_20210408_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='blogs_subcribe',
            field=models.ManyToManyField(blank=True, null=True, to='ubservs.Blog', verbose_name='Subscribed blogs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='read_posts',
            field=models.ManyToManyField(blank=True, null=True, to='ubservs.Post', verbose_name='Read news posts'),
        ),
    ]
